module PremierePoll.Data exposing (polls, samplePoll)

import PremierePoll as P

samplePoll : P.PremirePoll
samplePoll =
  {
    yearMonth = (2025, 12)
    , discipline = P.Open
    , ballots = P.parseBallotData dec25OpenData
  }

polls : List P.PremirePoll
polls =
  [ 
    { 
      yearMonth = (2025, 12)
      , discipline = P.Open
      , ballots = P.parseBallotData dec25OpenData
    }
  , {
      yearMonth = (2025, 11)
      , discipline = P.Open
      , ballots = P.parseBallotData nov25OpenData
    }
  , {
      yearMonth = (2025, 10)
      , discipline = P.Open
      , ballots = P.parseBallotData oct25OpenData
    }
  , {
      yearMonth = (2025, 10)
      , discipline = P.Das
      , ballots = P.parseBallotData oct25DasData
    }
  , {
      yearMonth = (2025, 7)
      , discipline = P.Das
      , ballots = P.parseBallotData jul25DasData
    }
  , {
      yearMonth = (2025, 9)
      , discipline = P.Tap
      , ballots = P.parseBallotData sep25TapData
    }
  ]


dec25OpenData : String
dec25OpenData = """
3arrett,BLUE SCUTI,ALEX T,DOG,PIXELANDY,FRACTAL,MEME,TRISTOP,SIDNEV,IBALL,NIGHT,MYLES,COBRA,TETRISTIME,SV,NEK0,THEDENGLER,COAL,GERALD FREEMAN,HUFFULUFUGUS,DANV,AKATU,TUGI,GWAFEY,SODIUM,EVESY
AdamIrish,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,NIGHT,SV,TRISTOP,SIDNEV,IBALL,COBRA,NEK0,MYLES,HUFFULUFUGUS,COAL,AKATU,FRACTAL,TUGI,THEDENGLER,TETRISTIME,EVESY,DANV,SODIUM,O,ID_KIRBY
Andrew Meep,BLUE SCUTI,DOG,ALEX T,MEME,PIXELANDY,NIGHT,SIDNEV,TRISTOP,SV,IBALL,AKATU,MYLES,HUFFULUFUGUS,NEK0,COBRA,COAL,GWAFEY,TETRISTIME,EVESY,TUGI,DANV,CRYTICALAPIS,THEDENGLER,WINTERRA,ID_KIRBY
arbaro,BLUE SCUTI,DOG,ALEX T,MEME,PIXELANDY,SIDNEV,NIGHT,SV,TRISTOP,COBRA,NEK0,MYLES,IBALL,TETRISTIME,COAL,HUFFULUFUGUS,DANV,AKATU,SODIUM,TUGI,WALLBANT,O,EVESY,ID_KIRBY,THEDENGLER
Grand Designs,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,SIDNEV,NIGHT,TRISTOP,SV,AKATU,MYLES,IBALL,HUFFULUFUGUS,COAL,COBRA,EVESY,NEK0,TETRISTIME,TUGI,DANV,GWAFEY,THEDENGLER,WINTERRA,CRYTICALAPIS,WALLBANT
Gunter,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,NIGHT,NEK0,FRACTAL,IBALL,COBRA,SV,TRISTOP,MYLES,SIDNEV,TETRISTIME,DANV,TUGI,SODIUM,THEDENGLER,HUFFULUFUGUS,COAL,O,AKATU,EVESY,PHLOXAE
Hecate,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,NIGHT,SIDNEV,SV,AKATU,IBALL,COBRA,TRISTOP,MYLES,TUGI,NEK0,SODIUM,WALLBANT,COAL,HUFFULUFUGUS,TETRISTIME,THEDENGLER,WINTERRA,DANV,CRYTICALAPIS,O
Jakub,ALEX T,DOG,BLUE SCUTI,PIXELANDY,MEME,SIDNEV,TRISTOP,MYLES,IBALL,FRACTAL,NIGHT,COAL,COBRA,HUFFULUFUGUS,DANV,TETRISTIME,SV,THEDENGLER,GWAFEY,AKATU,ALLENBOT,SOMALIAN,EVESY,ID_KIRBY,SUNNY
Jay,ALEX T,BLUE SCUTI,DOG,MEME,TRISTOP,PIXELANDY,IBALL,NIGHT,NEK0,FRACTAL,COBRA,THEDENGLER,SV,MYLES,COAL,HUFFULUFUGUS,TETRISTIME,TUGI,SODIUM,AKATU,EVESY,WALLBANT,DANV,DMJ,MASY
Kingsman,DOG,ALEX T,BLUE SCUTI,PIXELANDY,MEME,IBALL,SV,FRACTAL,NEK0,SIDNEV,COBRA,TRISTOP,AKATU,THEDENGLER,NIGHT,MYLES,COAL,HUFFULUFUGUS,SODIUM,MASY,EVESY,DANV,WALLBANT,WINTERRA,HYDRANTDUDE
Marfram,ALEX T,BLUE SCUTI,DOG,MEME,PIXELANDY,NIGHT,SV,SIDNEV,AKATU,NEK0,MYLES,TRISTOP,IBALL,TETRISTIME,COBRA,TUGI,DANV,CRYTICALAPIS,SODIUM,WALLBANT,THEDENGLER,O,ID_KIRBY,WINTERRA,PEEKAYRIC
Mathwiz100,BLUE SCUTI,PIXELANDY,DOG,ALEX T,MEME,SV,COAL,COBRA,FRACTAL,NIGHT,AKATU,TUGI,SODIUM,MYLES,THEDENGLER,HUFFULUFUGUS,TRISTOP,IBALL,NEK0,TETRISTIME,CRYTICALAPIS,GWAFEY,MASY,EVESY,HYDRANTDUDE
pumpyheart,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,IBALL,NIGHT,TRISTOP,SIDNEV,HUFFULUFUGUS,SV,MYLES,NEK0,COAL,COBRA,AKATU,TETRISTIME,FRACTAL,TUGI,GWAFEY,THEDENGLER,EVESY,SODIUM,OPAUX,WALLBANT
Richard Wolf VI,ALEX T,DOG,PIXELANDY,BLUE SCUTI,MEME,MYLES,COBRA,SV,SIDNEV,NEK0,TRISTOP,IBALL,COAL,AKATU,THEDENGLER,HUFFULUFUGUS,NIGHT,DANV,GWAFEY,TETRISTIME,WALLBANT,TUGI,SODIUM,ID_KIRBY,HYDRANTDUDE
roncli,ALEX T,BLUE SCUTI,DOG,PIXELANDY,MEME,TRISTOP,IBALL,FRACTAL,NIGHT,MYLES,SV,SIDNEV,NEK0,THEDENGLER,DANV,HUFFULUFUGUS,SODIUM,COAL,COBRA,EVESY,TUGI,O,TETRISTIME,ID_KIRBY,HYDRANTDUDE
rxs,BLUE SCUTI,DOG,ALEX T,MEME,PIXELANDY,TRISTOP,SIDNEV,SV,NIGHT,IBALL,AKATU,COBRA,HUFFULUFUGUS,COAL,MYLES,NEK0,TETRISTIME,GWAFEY,TUGI,DANV,SODIUM,EVESY,WALLBANT,ID_KIRBY,CRYTICALAPIS
Ryan Amburgy,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,NIGHT,SIDNEV,TRISTOP,SV,AKATU,IBALL,MYLES,HUFFULUFUGUS,COAL,COBRA,NEK0,TETRISTIME,GWAFEY,TUGI,DANV,EVESY,CRYTICALAPIS,WINTERRA,ID_KIRBY,MASY
stolenshortsword,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,SIDNEV,NIGHT,TRISTOP,SV,COBRA,NEK0,IBALL,AKATU,HUFFULUFUGUS,MYLES,GWAFEY,COAL,TETRISTIME,TUGI,DANV,THEDENGLER,WINTERRA,SODIUM,WALLBANT,MASY
Thisinthat,BLUE SCUTI,DOG,ALEX T,PIXELANDY,MEME,TRISTOP,SV,IBALL,FRACTAL,NIGHT,NEK0,AKATU,COAL,COBRA,MYLES,TUGI,HUFFULUFUGUS,SODIUM,DANV,SIDNEV,GWAFEY,THEDENGLER,TETRISTIME,WALLBANT,CRYTICALAPIS
vandweller,DOG,BLUE SCUTI,ALEX T,PIXELANDY,MEME,TRISTOP,NIGHT,IBALL,MYLES,THEDENGLER,NEK0,COBRA,SIDNEV,COAL,SV,FRACTAL,TUGI,HUFFULUFUGUS,TETRISTIME,AKATU,DANV,EVESY,WALLBANT,SODIUM,ID_KIRBY
Wingfryer,DOG,BLUE SCUTI,MEME,ALEX T,TRISTOP,IBALL,FRACTAL,SV,MYLES,PIXELANDY,THEDENGLER,COBRA,NIGHT,TETRISTIME,COAL,TUGI,GWAFEY,WALLBANT,HUFFULUFUGUS,DANV,SODIUM,AKATU,NEK0,NOWI,EVESY
"""

nov25OpenData : String
nov25OpenData = """
3arrett,ALEX T,DOG,BLUE SCUTI,PIXELANDY,FRACTAL,MEME,TRISTOP,SIDNEV,IBALL,MYLES,NEK0,COAL,THEDENGLER,GERALD FREEMAN,COBRA,NIGHT,TETRISTIME,SV,HUFFULUFUGUS,GWAFEY,DANV,SODIUM,SUNNY,EVESY,ZROBOT
AdamIrsh,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,TRISTOP,NEK0,NIGHT,IBALL,SV,COBRA,COAL,FRACTAL,HUFFULUFUGUS,MYLES,TETRISTIME,THEDENGLER,TUGI,EVESY,AKATU,SODIUM,HYDRANTDUDE,WALLBANT,O,MASY
Andrew Meep,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,TRISTOP,NIGHT,NEK0,IBALL,COBRA,SV,TETRISTIME,COAL,FRACTAL,HUFFULUFUGUS,MYLES,TUGI,O,THEDENGLER,SODIUM,AKATU,EVESY,DANV,CRYTICALAPIS,WALLBANT
arbaro,DOG,BLUE SCUTI,ALEX T,PIXELANDY,TRISTOP,MEME,NEK0,NIGHT,SV,TETRISTIME,IBALL,COBRA,DANV,MYLES,COAL,FRACTAL,THEDENGLER,HUFFULUFUGUS,TUGI,O,SODIUM,EVESY,CRYTICALAPIS,WALLBANT,GWAFEY
Grand Designs,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,TRISTOP,NEK0,NIGHT,COBRA,IBALL,SV,COAL,FRACTAL,TETRISTIME,HUFFULUFUGUS,MYLES,O,AKATU,EVESY,THEDENGLER,TUGI,WALLBANT,SODIUM,DANV,CRYTICALAPIS
Gunter,DOG,BLUE SCUTI,ALEX T,PIXELANDY,IBALL,FRACTAL,MEME,TRISTOP,NEK0,THEDENGLER,COAL,NIGHT,SV,MYLES,EVESY,SODIUM,DANV,HUFFULUFUGUS,COBRA,WALLBANT,O,TUGI,GWAFEY,TETRISTIME,SUNNY
Hecate,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,TRISTOP,NIGHT,IBALL,SV,COAL,TETRISTIME,EVESY,COBRA,TUGI,NEK0,FRACTAL,GWAFEY,HUFFULUFUGUS,MYLES,ID_KIRBY,AKATU,DANV,THEDENGLER,SODIUM,WALLBANT
Jakub,ALEX T,DOG,BLUE SCUTI,MEME,TRISTOP,PIXELANDY,IBALL,NIGHT,THEDENGLER,FRACTAL,SV,NEK0,TETRISTIME,MYLES,COBRA,COAL,DANV,AKATU,TUGI,HUFFULUFUGUS,SODIUM,EVESY,WALLBANT,OSCAR,ID_KIRBY
Kingsman,ALEX T,DOG,BLUE SCUTI,PIXELANDY,MEME,NEK0,IBALL,NIGHT,FRACTAL,SV,COBRA,MYLES,EVESY,COAL,THEDENGLER,SODIUM,TETRISTIME,DMJ,O,DANV,TUGI,NOWI,HYDRANTDUDE,WALLBANT,WINTERRA
Marfram,DOG,BLUE SCUTI,ALEX T,MEME,TRISTOP,PIXELANDY,HUFFULUFUGUS,NIGHT,FRACTAL,THEDENGLER,SUNNY,SV,IBALL,TETRISTIME,MYLES,ID_KIRBY,SODIUM,TUGI,DANV,COBRA,O,AKATU,CRYTICALAPIS,EVESY,WINTERRA
Mathwiz100,DOG,ALEX T,BLUE SCUTI,PIXELANDY,MEME,NEK0,IBALL,TRISTOP,FRACTAL,COBRA,COAL,SV,HUFFULUFUGUS,THEDENGLER,NIGHT,GWAFEY,EVESY,TUGI,WALLBANT,AKATU,HYDRANTDUDE,MYLES,MASY,TETRISTIME,SODIUM
pumpy,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,NEK0,TRISTOP,IBALL,NIGHT,THEDENGLER,HUFFULUFUGUS,SV,COBRA,TETRISTIME,COAL,MYLES,FRACTAL,TUGI,GWAFEY,O,SODIUM,OPAUX,WALLBANT,EVESY,AKATU
Richard Wolf VI,ALEX T,DOG,BLUE SCUTI,PIXELANDY,MEME,TRISTOP,IBALL,SV,AKATU,THEDENGLER,MYLES,NEK0,NIGHT,COBRA,DANV,SODIUM,TUGI,COAL,TETRISTIME,O,FRACTAL,WALLBANT,NOWI,OSCAR,HYDRANTDUDE
roncli,ALEX T,DOG,BLUE SCUTI,PIXELANDY,MEME,TRISTOP,IBALL,FRACTAL,NEK0,NIGHT,MYLES,SV,SIDNEV,THEDENGLER,O,TETRISTIME,DANV,HUFFULUFUGUS,SODIUM,COAL,COBRA,EVESY,TUGI,ID_KIRBY,GWAFEY
rxs,DOG,BLUE SCUTI,ALEX T,PIXELANDY,MEME,TRISTOP,NIGHT,NEK0,IBALL,COBRA,SV,AKATU,TETRISTIME,TUGI,HUFFULUFUGUS,COAL,FRACTAL,O,MYLES,EVESY,THEDENGLER,GWAFEY,DANV,SODIUM,CRYTICALAPIS
Ryan Amburgy,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,TRISTOP,NIGHT,NEK0,IBALL,COBRA,TETRISTIME,SV,COAL,FRACTAL,HUFFULUFUGUS,AKATU,MYLES,O,TUGI,THEDENGLER,EVESY,SODIUM,HYDRANTDUDE,DANV,CRYTICALAPIS
stolenshortsword,DOG,BLUE SCUTI,ALEX T,MEME,PIXELANDY,TRISTOP,NIGHT,NEK0,IBALL,SV,TETRISTIME,COBRA,COAL,HUFFULUFUGUS,FRACTAL,MYLES,TUGI,O,THEDENGLER,SODIUM,AKATU,DANV,WALLBANT,CRYTICALAPIS,EVESY
Thisinthat,DOG,BLUE SCUTI,ALEX T,MEME,PIXELANDY,IBALL,TRISTOP,FRACTAL,NEK0,COAL,COBRA,HUFFULUFUGUS,COAL,MYLES,SV,GWAFEY,THEDENGLER,DANV,WALLBANT,HYDRANTDUDE,GERALD FREEMAN,ALLENBOT,SODIUM,TUGI,NIGHT
vandweller,DOG,ALEX T,BLUE SCUTI,PIXELANDY,TRISTOP,MEME,IBALL,NIGHT,THEDENGLER,NEK0,MYLES,FRACTAL,COBRA,SV,COAL,TETRISTIME,SIDNEV,HUFFULUFUGUS,TUGI,EVESY,DANV,SODIUM,AKATU,O,WALLBANT
Wingfryer,DOG,ALEX T,BLUE SCUTI,MEME,TRISTOP,IBALL,FRACTAL,MYLES,PIXELANDY,THEDENGLER,COAL,SV,COBRA,NIGHT,TETRISTIME,TUGI,GWAFEY,HUFFULUFUGUS,WALLBANT,SODIUM,DANV,AKATU,NEK0,NOWI,EVESY
"""

oct25OpenData : String
oct25OpenData = """
3arrett,DOG,BLUE SCUTI,ALEX T,PIXELANDY,MEME,FRACTAL,SIDNEV,TRISTOP,IBALL,COAL,THEDENGLER,MYLES,NEK0,GERALD FREEMAN,COBRA,NIGHT,HUFFULUFUGUS,SV,TETRISTIME,PORTALLL,GWAFEY,EVESY,DANV,ZROBOT,SUNNY
AdamIrish,DOG,ALEX T,BLUE SCUTI,PIXELANDY,MEME,TRISTOP,NEK0,NIGHT,IBALL,COBRA,SV,COAL,FRACTAL,MYLES,HUFFULUFUGUS,EVESY,GWAFEY,TETRISTIME,THEDENGLER,SODIUM,SUNNY,WALLBANT,CRYTICALAPIS,HYDRANTDUDE,TUGI
Andrew Meep,DOG,BLUE SCUTI,ALEX T,PIXELANDY,MEME,TRISTOP,NIGHT,IBALL,COAL,NEK0,FRACTAL,MYLES,THEDENGLER,COBRA,HUFFULUFUGUS,SV,EVESY,GWAFEY,SUNNY,O,TETRISTIME,ID_KIRBY,PEEKAYRIC,WALLBANT,CRYTICALAPIS
arbaro,DOG,ALEX T,BLUE SCUTI,PIXELANDY,TRISTOP,MEME,NEK0,IBALL,NIGHT,SV,FRACTAL,THEDENGLER,COBRA,COAL,HUFFULUFUGUS,MYLES,SODIUM,EVESY,GWAFEY,DANV,SUNNY,TETRISTIME,TUGI,WALLBANT,HYDRANTDUDE
Grand Designs,DOG,ALEX T,PIXELANDY,BLUE SCUTI,MEME,TRISTOP,NEK0,IBALL,COAL,NIGHT,FRACTAL,MYLES,COBRA,THEDENGLER,EVESY,SV,HUFFULUFUGUS,O,GWAFEY,TETRISTIME,SODIUM,ID_KIRBY,CRYTICALAPIS,SUNNY,WALLBANT
Gunter,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,TRISTOP,IBALL,FRACTAL,NEK0,COAL,SV,COBRA,MYLES,EVESY,HUFFULUFUGUS,NIGHT,THEDENGLER,WALLBANT,O,GWAFEY,SUNNY,PORTALLL,TETRISTIME,VICIOUS RHUBARB,DANV
Hecate,ALEX T,DOG,BLUE SCUTI,MEME,PIXELANDY,NIGHT,NEK0,TRISTOP,IBALL,COAL,SV,WALLBANT,GWAFEY,EVESY,THEDENGLER,FRACTAL,DANV,MYLES,COBRA,SODIUM,TUGI,SUNNY,HUFFULUFUGUS,CRYTICALAPIS,TETRISTIME
Kingsman,ALEX T,DOG,MEME,BLUE SCUTI,PIXELANDY,NEK0,IBALL,TRISTOP,EVESY,FRACTAL,THEDENGLER,SV,SODIUM,MYLES,COAL,NIGHT,COBRA,DANV,HUFFULUFUGUS,O,HYDRANTDUDE,TETRISTIME,DMJ,TUGI,WINTERRA
Mathwiz100,DOG,BLUE SCUTI,PIXELANDY,ALEX T,MEME,IBALL,NEK0,COAL,NIGHT,THEDENGLER,HUFFULUFUGUS,FRACTAL,EVESY,SV,SODIUM,GWAFEY,WALLBANT,TETRISTIME,TRISTOP,MYLES,DANV,HYDRANTDUDE,CRYTICALAPIS,SIDNEV,GERALD FREEMAN
pumpyheart,DOG,ALEX T,BLUE SCUTI,MEME,PIXELANDY,IBALL,COAL,NEK0,TRISTOP,THEDENGLER,HUFFULUFUGUS,MYLES,COBRA,FRACTAL,SV,NIGHT,VICIOUS RHUBARB,SODIUM,TUGI,OPAUX,WALLBANT,EVESY,GWAFEY,SUNNY,O
Richard WolfVI,ALEX T,DOG,BLUE SCUTI,PIXELANDY,MEME,IBALL,NEK0,SODIUM,NIGHT,THEDENGLER,MYLES,SV,GWAFEY,COAL,FRACTAL,TUGI,ID_KIRBY,HYDRANTDUDE,EVESY,DANV,HUFFULUFUGUS,TETRISTIME,COBRA,WALLBANT,VICIOUS RHUBARB
Roman Michell,DOG,ALEX T,BLUE SCUTI,PIXELANDY,MEME,TRISTOP,NIGHT,NEK0,IBALL,COAL,COBRA,FRACTAL,THEDENGLER,MYLES,SIDNEV,SV,GWAFEY,EVESY,TETRISTIME,VICIOUS RHUBARB,SODIUM,DANV,O,ID_KIRBY,SUNNY
roncli,ALEX T,DOG,PIXELANDY,BLUE SCUTI,MEME,TRISTOP,IBALL,FRACTAL,NEK0,THEDENGLER,NIGHT,MYLES,SV,SIDNEV,SODIUM,O,DANV,HUFFULUFUGUS,COAL,TETRISTIME,COBRA,EVESY,ID_KIRBY,GWAFEY,WALLBANT
rxs,DOG,BLUE SCUTI,ALEX T,PIXELANDY,MEME,TRISTOP,NEK0,THEDENGLER,COAL,GWAFEY,COBRA,NIGHT,FRACTAL,MYLES,SV,EVESY,SODIUM,TETRISTIME,TUGI,HUFFULUFUGUS,WALLBANT,SUNNY,O,DANV,CRYTICALAPIS
Ryan Amburgy,DOG,BLUE SCUTI,ALEX T,PIXELANDY,MEME,TRISTOP,NEK0,NIGHT,COAL,IBALL,THEDENGLER,FRACTAL,COBRA,MYLES,HUFFULUFUGUS,SV,EVESY,GWAFEY,O,ID_KIRBY,SODIUM,TETRISTIME,SUNNY,CRYTICALAPIS,POHONJATI
SirMaser,ALEX T,DOG,BLUE SCUTI,MEME,TRISTOP,PIXELANDY,IBALL,COAL,NEK0,FRACTAL,NIGHT,MYLES,HUFFULUFUGUS,COBRA,SV,EVESY,GWAFEY,TETRISTIME,THEDENGLER,DANV,WALLBANT,SODIUM,SUNNY,TUGI,PORTALLL
stolenshortsword,DOG,BLUE SCUTI,PIXELANDY,ALEX T,MEME,TRISTOP,NEK0,NIGHT,IBALL,THEDENGLER,SV,FRACTAL,COBRA,HUFFULUFUGUS,COAL,SODIUM,MYLES,EVESY,GWAFEY,ID_KIRBY,SUNNY,CRYTICALAPIS,TETRISTIME,HYDRANTDUDE,O
Thisinthat,DOG,PIXELANDY,BLUE SCUTI,ALEX T,MEME,IBALL,NEK0,TRISTOP,COAL,FRACTAL,NIGHT,COBRA,THEDENGLER,MYLES,SV,GWAFEY,SODIUM,EVESY,HUFFULUFUGUS,DANV,HYDRANTDUDE,WALLBANT,SUNNY,CRYTICALAPIS,MASY
Wingfryer,ALEX T,DOG,BLUE SCUTI,MEME,TRISTOP,IBALL,FRACTAL,MYLES,THEDENGLER,COAL,PIXELANDY,SV,COBRA,TETRISTIME,NIGHT,TUGI,HUFFULUFUGUS,GWAFEY,SODIUM,DANV,WALLBANT,NEK0,SUNNY,NOWI,EVESY
"""

oct25DasData : String
oct25DasData = """
3arrett,PIXELANDY,GIOVANNI,LIOLIO,FRACTAL,DOG,TUGI,BLUE SCUTI,BENDY1,MORKOS,ADAM,SHARKY,ROBIN,TOMMYNTG,NGC MAN,SALTEDSOFA,GREENTEA,NENU,ELIAS,SCOTTOBOZO,ALEX T
arbaro,GIOVANNI,PIXELANDY,LIOLIO,TUGI,BLUE SCUTI,ROBIN,FRACTAL,NENU,AVGEEK,DOG,MORKOS,BENDY1,ELIAS,SCOTTOBOZO,CHROMA,TEGAMECH,USERNAMEGOLD,WALLBANT,ADAM,MEME
Gunter,PIXELANDY,GIOVANNI,LIOLIO,TUGI,BLUE SCUTI,FRACTAL,MORKOS,DOG,BENDY1,NENU,ROBIN,ADAM,SHUICHI,SHARKY,NGC MAN,TEGAMECH,TOMMYNTG,AVGEEK,ELIAS,SALTEDSOFA
hana,PIXELANDY,GIOVANNI,BLUE SCUTI,TUGI,FRACTAL,LIOLIO,DOG,BENDY1,ROBIN,ADAM,NENU,TEGAMECH,MORKOS,SHARKY,MEME,AVGEEK,TOMMYNTG,WALLBANT,ELIAS,USERNAMEGOLD
Hecate,PIXELANDY,GIOVANNI,LIOLIO,ROBIN,BENDY1,FRACTAL,BLUE SCUTI,TUGI,DOG,MORKOS,AVGEEK,TEGAMECH,NENU,WALLBANT,ADAM,SHUICHI,ELIAS,SV,NGC MAN,SCOTTOBOZO
Kingsman,PIXELANDY,GIOVANNI,DOG,LIOLIO,ROBIN,FRACTAL,BENDY1,TUGI,SALTEDSOFA,ADAM,NENU,BLUE SCUTI,AVGEEK,MEME,PEEKAYRIC,SHARKY,NIGHT,ELIAS,MICETRO,TORZSA
Richard Wolf VI,PIXELANDY,GIOVANNI,FRACTAL,TUGI,LIOLIO,BENDY1,NENU,MORKOS,ROBIN,ELIAS,SCOTTOBOZO,OEUFMEANSEGG,NIGHT,DOG,BLUE SCUTI,AVGEEK,MEME,PEEKAYRIC,USERNAMEGOLD,CHROMA
Roman Michell,PIXELANDY,GIOVANNI,LIOLIO,FRACTAL,DOG,TUGI,BENDY1,ROBIN,NENU,BLUE SCUTI,SHARKY,ADAM,AVGEEK,SALTEDSOFA,SCOTTOBOZO,PEEKAYRIC,MORKOS,CHROMA,TEGAMECH,MICETRO
rxs,PIXELANDY,GIOVANNI,LIOLIO,TUGI,DOG,NENU,BENDY1,AVGEEK,PEEKAYRIC,FRACTAL,ELIAS,BLUE SCUTI,CHROMA,ROBIN,USERNAMEGOLD,TORZSA,SHARKY,SCOTTOBOZO,TEGAMECH,WALLBANT
Ryan Amburgy,PIXELANDY,GIOVANNI,BENDY1,LIOLIO,FRACTAL,TUGI,DOG,NENU,BLUE SCUTI,ROBIN,SHARKY,SALTEDSOFA,CHROMA,AVGEEK,MORKOS,PEEKAYRIC,HUFFULUFUGUS,SCOTTOBOZO,ELIAS,COAL
Thisinthat,PIXELANDY,GIOVANNI,LIOLIO,FRACTAL,BENDY1,TUGI,DOG,MORKOS,ROBIN,AVGEEK,BLUE SCUTI,SALTEDSOFA,NENU,ELIAS,TEGAMECH,SCOTTOBOZO,NGC MAN,NIGHT,MEME,SERENITYINSORROW
"""

jul25DasData : String
jul25DasData = """
3arrett,PIXELANDY,GIOVANNI,FRACTAL,DOG,LIOLIO,SHARKY,BENDY1,TUGI,MORKOS,ADAM,TOMMYNTG,SALTEDSOFA,NGC MAN,ROBIN,GREENTEA,BLUE SCUTI,ELIAS,NENU,SCOTTOBOZO,TEGAMECH
arbaro,PIXELANDY,GIOVANNI,LIOLIO,MORKOS,DOG,FRACTAL,BENDY1,TUGI,ELIAS,TOMMYNTG,ROBIN,NENU,SCOTTOBOZO,AVGEEK,SALTEDSOFA,SHARKY,BLUE SCUTI,NGC MAN,NIGHT,WALLBANT
Gunter,PIXELANDY,GIOVANNI,LIOLIO,TUGI,TOMMYNTG,MORKOS,DOG,SHARKY,BENDY1,FRACTAL,MEME,AVGEEK,SALTEDSOFA,ELIAS,SV,TEGAMECH,CHILLER,ROBIN,MATT MARTIN,NGC MAN
hana,GIOVANNI,PIXELANDY,FRACTAL,LIOLIO,DOG,BENDY1,MORKOS,TUGI,TOMMYNTG,ROBIN,NENU,SALTEDSOFA,NGC MAN,SCOTTOBOZO,BLUE SCUTI,TEGAMECH,AVGEEK,ELIAS,MYLES,WALLBANT
Hecate,PIXELANDY,GIOVANNI,BENDY1,LIOLIO,MORKOS,DOG,FRACTAL,BLUE SCUTI,TUGI,ROBIN,NGC MAN,JDH,WALLBANT,SCOTTOBOZO,ELIAS,AVGEEK,NIGHT,MEME,MYLES,NENU
Kingsman,PIXELANDY,GIOVANNI,ROBIN,FRACTAL,DOG,LIOLIO,TEGAMECH,BENDY1,SALTEDSOFA,AVGEEK,ELIAS,TRISTOP,NIGHT,SHARKY,TUGI,MYLES,NENU,NGC MAN,TRISKAI,BLUE SCUTI
Marfram,PIXELANDY,GIOVANNI,FRACTAL,LIOLIO,TOMMYNTG,BLUE SCUTI,BENDY1,DOG,NENU,TUGI,MORKOS,JDH,NIGHT,SALTEDSOFA,NGC MAN,SV,TEGAMECH,AVGEEK,USERNAMEGOLD,MEME
Richard Wolf VI,PIXELANDY,FRACTAL,GIOVANNI,TUGI,MORKOS,BENDY1,SALTEDSOFA,ROBIN,SCOTTOBOZO,ELIAS,NIGHT,OEUFMEANSEGG,MEME,DOG,AVGEEK,LIOLIO,TEGAMECH,NENU,SHARKY,JDH
rxs,PIXELANDY,GIOVANNI,FRACTAL,DOG,LIOLIO,TUGI,MORKOS,BENDY1,TOMMYNTG,ELIAS,NGC MAN,ROBIN,NENU,SALTEDSOFA,BLUE SCUTI,AVGEEK,SCOTTOBOZO,USERNAMEGOLD,NIGHT,TEGAMECH
Ryan Amburgy,PIXELANDY,GIOVANNI,FRACTAL,BENDY1,TUGI,LIOLIO,DOG,MORKOS,ROBIN,TOMMYNTG,WALLBANT,BLUE SCUTI,NGC MAN,SALTEDSOFA,SCOTTOBOZO,NENU,ELIAS,JDH,MYLES,USERNAMEGOLD
Sonic,PIXELANDY,GIOVANNI,LIOLIO,MORKOS,BENDY1,FRACTAL,DOG,TUGI,ROBIN,TOMMYNTG,SCOTTOBOZO,ELIAS,SALTEDSOFA,AVGEEK,NENU,BLUE SCUTI,NGC MAN,JDH,WALLBANT,NIGHT
vandweller,PIXELANDY,GIOVANNI,BENDY1,LIOLIO,ROBIN,DOG,FRACTAL,ELIAS,AVGEEK,TUGI,BLUE SCUTI,NENU,SHARKY,MORKOS,SCOTTOBOZO,MEME,MATT MARTIN,TOMMYNTG,OEUFMEANSEGG,NIGHT
Zempro,PIXELANDY,GIOVANNI,FRACTAL,LIOLIO,TUGI,MORKOS,BENDY1,DOG,TOMMYNTG,SALTEDSOFA,BLUE SCUTI,ROBIN,NENU,ELIAS,NGC MAN,SCOTTOBOZO,WALLBANT,USERNAMEGOLD,JDH,MYLES
"""

sep25TapData : String
sep25TapData = """
3arrett,ALEX T,MOJA,DOG,BLUE SCUTI,JOSEPH,PIXELANDY,BRODINDAMP,DILLAN,FRACTAL,EREN,ERICICX,IBALL,BENDY1,ATKOSTER,SIDNEV,VICIOUS RHUBARB,TRAPZONE,KORYAN,MASY,SOMALIAN
Gunter,ALEX T,DOG,BLUE SCUTI,JOSEPH,DILLAN,ATKOSTER,EREN,BENDY1,PIXELANDY,IBALL,ERICICX,TRAPZONE,OSCAR,MASY,KLEIN,OPAUX,CRYTICALAPIS,CHILLER,SOMALIAN,MARQ
Kingsman,ALEX T,DOG,JOSEPH,DILLAN,ATKOSTER,BLUE SCUTI,IBALL,BENDY1,ERICICX,EREN,TRAPZONE,KLEIN,TSTORM,TETRISTIME,EVESY,MASY,WINTERRA,FRACTAL,PIXELANDY,KORYAN
pumpyheart,ALEX T,DOG,JOSEPH,DILLAN,ATKOSTER,EREN,BLUE SCUTI,PIXELANDY,BENDY1,BRODINDAMP,TRAPZONE,IBALL,ERICICX,FRACTAL,MASY,SOMALIAN,KORYAN,EVESY,KLEIN,VICIOUS RHUBARB
Richard Wolf VI,ALEX T,DOG,JOSEPH,ATKOSTER,BLUE SCUTI,BENDY1,DILLAN,IBALL,PIXELANDY,EREN,ERICICX,CRYTICALAPIS,MASY,OSCAR,TRAPZONE,BRODINDAMP,FRACTAL,OPAUX,VICIOUS RHUBARB,SOMALIAN
Roman Michell,ALEX T,DOG,JOSEPH,ATKOSTER,DILLAN,BLUE SCUTI,EREN,IBALL,BENDY1,PIXELANDY,PIXELANDY,BRODINDAMP,TRAPZONE,ERICICX,MASY,FRACTAL,KLEIN,CHROMA,SOMALIAN,VICIOUS RHUBARB
rxs,ALEX T,DOG,JOSEPH,DILLAN,BLUE SCUTI,ATKOSTER,BENDY1,EREN,BRODINDAMP,IBALL,PIXELANDY,TRAPZONE,KLEIN,ERICICX,MASY,SOMALIAN,CRYTICALAPIS,EVESY,TSTORM,CHROMA
Ryan Amburgy,ALEX T,DOG,DILLAN,JOSEPH,ATKOSTER,BLUE SCUTI,EREN,BENDY1,PIXELANDY,BRODINDAMP,IBALL,ERICICX,TRAPZONE,FRACTAL,EVESY,MASY,KLEIN,SOMALIAN,CHROMA,VICIOUS RHUBARB
Thisinthat,ALEX T,DOG,JOSEPH,BLUE SCUTI,FRACTAL,ATKOSTER,IBALL,PIXELANDY,DILLAN,ERICICX,MASY,CRYTICALAPIS,BENDY1,HUFFULUFUGUS,OPAUX,OSCAR,TUGI,MYLES,SOMALIAN,TSTORM"""